#!/usr/bin/env bash
# Prepares an Ubuntu 24.04 LTS host for GPU-enabled Kubernetes: packages, Secure Boot check, GPU visibility.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"
[[ -f "$SCRIPT_DIR/../config.env" ]] && source "$SCRIPT_DIR/../config.env"

require_cmd sudo
require_cmd lspci

log "Updating apt package index"
sudo apt-get update -y

log "Upgrading existing packages"
sudo apt-get upgrade -y

log "Installing base packages"
sudo apt-get install -y \
  curl wget gnupg ca-certificates software-properties-common \
  build-essential dkms "linux-headers-$(uname -r)" jq gettext-base \
  ubuntu-drivers-common apt-transport-https openssh-server

log "Checking for an NVIDIA GPU on the PCI bus"
# Capture lspci once rather than piping into `grep -q`: grep exits at the first match,
# lspci takes SIGPIPE, and `set -o pipefail` then reports 141 for the whole pipeline -
# so the check would fail exactly when the GPU *was* found.
PCI_DEVICES="$(lspci)"
if ! grep -qi nvidia <<<"$PCI_DEVICES"; then
  die "No NVIDIA device found via lspci. Check GPU seating/BIOS before continuing."
fi
grep -i nvidia <<<"$PCI_DEVICES"

if command -v mokutil >/dev/null 2>&1 && grep -qi enabled <<<"$(mokutil --sb-state 2>/dev/null)"; then
  warn "Secure Boot is enabled. NVIDIA kernel modules commonly fail to load with Secure Boot on."
  warn "Disable Secure Boot in BIOS/UEFI, or enroll the MOK key generated by DKMS after driver install."
fi

if [[ -f /var/run/reboot-required ]]; then
  warn "A reboot is required before continuing (kernel/package updates were applied)."
fi

log "Host preparation complete."
