#!/usr/bin/env bash
# Prepares an Ubuntu 24.04 LTS host for GPU-enabled Kubernetes: packages, Secure Boot check, GPU visibility.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"
[[ -f "$SCRIPT_DIR/../config.env" ]] && source "$SCRIPT_DIR/../config.env"

require_cmd sudo
require_cmd lspci

log "Updating apt package index"
sudo apt-get update -y

log "Upgrading existing packages"
sudo apt-get upgrade -y

log "Installing base packages"
sudo apt-get install -y \
  curl wget gnupg ca-certificates software-properties-common \
  build-essential dkms "linux-headers-$(uname -r)" jq gettext-base \
  ubuntu-drivers-common apt-transport-https openssh-server

log "Checking for an NVIDIA GPU on the PCI bus"
if ! lspci | grep -qi nvidia; then
  die "No NVIDIA device found via lspci. Check GPU seating/BIOS before continuing."
fi
lspci | grep -i nvidia

if command -v mokutil >/dev/null 2>&1 && mokutil --sb-state 2>/dev/null | grep -qi enabled; then
  warn "Secure Boot is enabled. NVIDIA kernel modules commonly fail to load with Secure Boot on."
  warn "Disable Secure Boot in BIOS/UEFI, or enroll the MOK key generated by DKMS after driver install."
fi

if [[ -f /var/run/reboot-required ]]; then
  warn "A reboot is required before continuing (kernel/package updates were applied)."
fi

log "Host preparation complete."
